/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fid.Tela;


import javax.swing.JOptionPane;
import com.fid.classes.Usuario;
import com.fid.classes.UsuarioModel;
import com.fid.conexao.UsuarioDAO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;


/**
 *
 * @author JEFFERSON
 */
public class TelaCadastroUsuario extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeCompleto = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblPerfil = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDelatar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        JScrollPane1 = new javax.swing.JScrollPane();
        tbListaPesquisa = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Usuario");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblNomeCompleto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNomeCompleto.setText("Nome Completo");

        txtNomeCompleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeCompletoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Usuario");

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSenha.setText("Senha");

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });

        lblPerfil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPerfil.setText("Perfil");

        txtPerfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPerfilKeyPressed(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/Save_icon-icons.com_73702.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        btnAdicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicionarKeyPressed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/Save-as_37111.png"))); // NOI18N
        btnEditar.setEnabled(false);

        btnDelatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/emptytrash_36203.png"))); // NOI18N
        btnDelatar.setEnabled(false);
        btnDelatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelatarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/Clear_37294.png"))); // NOI18N
        btnLimpar.setMaximumSize(new java.awt.Dimension(81, 23));
        btnLimpar.setMinimumSize(new java.awt.Dimension(81, 23));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/view_search_find_9565.png"))); // NOI18N
        btnPesquisar.setMaximumSize(new java.awt.Dimension(81, 23));
        btnPesquisar.setMinimumSize(new java.awt.Dimension(81, 23));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
        });

        tbListaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbListaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaPesquisaMouseClicked(evt);
            }
        });
        JScrollPane1.setViewportView(tbListaPesquisa);

        lblId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblId.setText("ID");

        txtId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPerfil)
                            .addComponent(lblNomeCompleto)
                            .addComponent(txtPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSenha)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelatar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblNomeCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelatar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(473, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
    int add = JOptionPane.showConfirmDialog(null, "Deseja salvar este contato?","Atenção",JOptionPane.YES_NO_OPTION);
        if( add == JOptionPane.YES_OPTION){
            adicionar();
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnDelatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelatarActionPerformed
       int add = JOptionPane.showConfirmDialog(null, "Deseja salvar este contato?","Atenção",JOptionPane.YES_NO_OPTION);
        if( add == JOptionPane.YES_OPTION){
            deletar();
        }
        
    }//GEN-LAST:event_btnDelatarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
         if (txtNomeCompleto.getText().isEmpty() && txtUsuario.getText().isEmpty() &&  txtSenha.getText().isEmpty() &&  txtPerfil.getText().isEmpty() ){
            txtNomeCompleto.requestFocus();
            
        }else{
            int add = JOptionPane.showConfirmDialog(null, "Tem Certeza que deseja limpar todos os campos de contato?","Atenção",JOptionPane.YES_NO_OPTION);
            if( add == JOptionPane.YES_OPTION){
            limpar();
        }
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            pesquisar();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
        try {
            pesquisar();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPesquisarKeyPressed

    private void tbListaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaPesquisaMouseClicked
        if(evt.getClickCount() == 2){
            setarCampos(); 
        }
    }//GEN-LAST:event_tbListaPesquisaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (tbListaPesquisa.getColumnCount() == 0){
            List<Usuario> usuarios = new ArrayList<>(); 
            UsuarioModel model = new UsuarioModel(usuarios);
            tbListaPesquisa.setModel(model);
            indiceTabela();
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtNomeCompletoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCompletoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
            txtUsuario.requestFocus();
         }
    }//GEN-LAST:event_txtNomeCompletoKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
            txtSenha.requestFocus();
         }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
            txtPerfil.requestFocus();
         }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtPerfilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPerfilKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             btnAdicionar.requestFocus();
         }
    }//GEN-LAST:event_txtPerfilKeyPressed

    private void btnAdicionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             adicionar();
         }
    }//GEN-LAST:event_btnAdicionarKeyPressed

    
    
     private void adicionar(){
        if (txtNomeCompleto.getText().isEmpty() && txtUsuario.getText().isEmpty() &&  txtSenha.getText().isEmpty() &&  txtPerfil.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Impossivel cadastar contato por favor preencha todos os campos"); 
        }else{
            
            Usuario usuarios = new Usuario();
            usuarios.setNome(txtNomeCompleto.getText());
            usuarios.setLogin(txtUsuario.getText());
            usuarios.setSenha( txtSenha.getText());
            usuarios.setPerfil(txtPerfil.getText());
            UsuarioDAO usuDao = new UsuarioDAO();
            usuDao.adicionar(usuarios);
            
        }
    
    }  
    
      private void deletar(){
        
        int usuId = Integer.parseInt(txtId.getText());
        
        Usuario usuarios = new Usuario();
        
        usuarios.setId(usuId);
        UsuarioDAO usuDao = new UsuarioDAO();
        usuDao.deletar(usuarios);
        limpar();
       
    }
      
      private void limpar(){
       txtId.setText("");
       txtNomeCompleto.setText("");
       txtUsuario.setText("");
       txtSenha.setText("");
       txtPerfil.setText("");
       
       
       txtNomeCompleto.requestFocus();
       btnAdicionar.setEnabled(true);
       btnDelatar.setEnabled(false);
       btnEditar.setEnabled(false);
    }

      private void indiceTabela(){
         tbListaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(40); 
         tbListaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(250); 
         tbListaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(150); 
         tbListaPesquisa.getColumnModel().getColumn(3).setPreferredWidth(150); 
         tbListaPesquisa.getColumnModel().getColumn(4).setPreferredWidth(150);
         
         tbListaPesquisa.getTableHeader().setReorderingAllowed(false); 
         tbListaPesquisa.setAutoResizeMode(tbListaPesquisa.AUTO_RESIZE_OFF);
    }

    private void pesquisar() throws Exception{
         List<Usuario> usuarios = new UsuarioDAO().pesquisar(txtPesquisar.getText());
         UsuarioModel umodel = new UsuarioModel(usuarios);
         tbListaPesquisa.setModel(umodel);
         indiceTabela();
         
    
    }   
    
    private void setarCampos(){
        int setar = tbListaPesquisa.getSelectedRow();
        txtId.setText(tbListaPesquisa.getModel().getValueAt(setar, 0).toString());
        txtNomeCompleto.setText(tbListaPesquisa.getModel().getValueAt(setar, 1).toString());
        txtUsuario.setText(tbListaPesquisa.getModel().getValueAt(setar, 2).toString());
        txtSenha.setText(tbListaPesquisa.getModel().getValueAt(setar, 3).toString());
        txtPerfil.setText(tbListaPesquisa.getModel().getValueAt(setar, 4).toString());
       
        
        
        btnAdicionar.setEnabled(false);
        btnDelatar.setEnabled(true);
        btnEditar.setEnabled(true);
    } 
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroUsuario dialog = new TelaCadastroUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnDelatar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTable tbListaPesquisa;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtPerfil;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    public static JLabel idusu = new JLabel();
}
