/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fid.Tela;

import com.fid.classes.Contatos;
import com.fid.classes.ContatosModel;
import com.fid.conexao.ContatosDAO;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author JEFFERSON
 */
public class TelaCadastroContato extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroContato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSkype = new javax.swing.JLabel();
        txtSkype = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        deskPaineFoto = new javax.swing.JDesktopPane();
        lblFoto = new javax.swing.JLabel();
        btnAdicionarFoto = new javax.swing.JButton();
        btnRemoverFoto = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDelatar = new javax.swing.JButton();
        JScrollPane1 = new javax.swing.JScrollPane();
        tbListaPesquisa = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();

        setTitle("Cadastrar Contato");
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblId.setText("ID");

        txtId.setEnabled(false);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNome.setText("Nome de Contato");

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelefone.setText("Telefone");

        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyPressed(evt);
            }
        });

        lblCelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCelular.setText("Celular");

        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelularKeyPressed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        lblSkype.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSkype.setText("Skype");

        txtSkype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSkypeKeyPressed(evt);
            }
        });

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEndereco.setText("Endereço");

        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyPressed(evt);
            }
        });

        lblBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBairro.setText("Bairro");

        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBairroKeyPressed(evt);
            }
        });

        lblCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCidade.setText("Cidade");

        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCidadeKeyPressed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEstado.setText("Estado");

        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEstadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });

        lblCep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCep.setText("CEP");

        txtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCepKeyPressed(evt);
            }
        });

        deskPaineFoto.setLayer(lblFoto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskPaineFotoLayout = new javax.swing.GroupLayout(deskPaineFoto);
        deskPaineFoto.setLayout(deskPaineFotoLayout);
        deskPaineFotoLayout.setHorizontalGroup(
            deskPaineFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deskPaineFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        deskPaineFotoLayout.setVerticalGroup(
            deskPaineFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPaineFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAdicionarFoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdicionarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/folder_images_36184(1).png"))); // NOI18N
        btnAdicionarFoto.setFocusable(false);
        btnAdicionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarFotoActionPerformed(evt);
            }
        });
        btnAdicionarFoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicionarFotoKeyPressed(evt);
            }
        });

        btnRemoverFoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemoverFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/Remove_Image_icon-icons.com_54146(1).png"))); // NOI18N
        btnRemoverFoto.setFocusable(false);
        btnRemoverFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFotoActionPerformed(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/Save_icon-icons.com_73702.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        btnAdicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicionarKeyPressed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/Clear_37294.png"))); // NOI18N
        btnLimpar.setMaximumSize(new java.awt.Dimension(81, 23));
        btnLimpar.setMinimumSize(new java.awt.Dimension(81, 23));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        btnLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLimparKeyPressed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/Save-as_37111.png"))); // NOI18N
        btnEditar.setEnabled(false);

        btnDelatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/emptytrash_36203.png"))); // NOI18N
        btnDelatar.setEnabled(false);
        btnDelatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelatarActionPerformed(evt);
            }
        });

        tbListaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbListaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaPesquisaMouseClicked(evt);
            }
        });
        JScrollPane1.setViewportView(tbListaPesquisa);

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/view_search_find_9565.png"))); // NOI18N
        btnPesquisar.setMaximumSize(new java.awt.Dimension(81, 23));
        btnPesquisar.setMinimumSize(new java.awt.Dimension(81, 23));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        btnPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPesquisarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(lblEmail)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblSkype)
                                                    .addGap(301, 301, 301))
                                                .addComponent(txtSkype)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblId)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNome)
                                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblTelefone)
                                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblCelular)
                                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                                .addComponent(lblEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(lblCidade))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBairro)
                                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblEstado))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(lblCep))))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(deskPaineFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdicionarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnRemoverFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelatar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(deskPaineFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRemoverFoto)
                            .addComponent(btnAdicionarFoto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSkype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSkype)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelatar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarFotoActionPerformed
       adicionarFoto();
    }//GEN-LAST:event_btnAdicionarFotoActionPerformed

    private void btnRemoverFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFotoActionPerformed
        
        int add = JOptionPane.showConfirmDialog(null, "Tem Certeza que deseja excluir foto de contato?","Atenção",JOptionPane.YES_NO_OPTION);
        if( add == JOptionPane.YES_OPTION){
            lblFoto.setIcon(null);
        }
    }//GEN-LAST:event_btnRemoverFotoActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        int add = JOptionPane.showConfirmDialog(null, "Deseja salvar este contato?","Atenção",JOptionPane.YES_NO_OPTION);
        if( add == JOptionPane.YES_OPTION){
            adicionar();
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        if (txtNome.getText().isEmpty() && txtTelefone.getText().isEmpty() &&  txtCelular.getText().isEmpty() &&  txtEmail.getText().isEmpty() && txtSkype.getText().isEmpty() && txtEndereco.getText().isEmpty() && txtBairro.getText().isEmpty() && txtCidade.getText().isEmpty() && txtEstado.getText().isEmpty() && txtCep.getText().isEmpty()){
            txtNome.requestFocus();
       
        }else{
            int add = JOptionPane.showConfirmDialog(null, "Tem Certeza que deseja limpar todos os campos de contato?","Atenção",JOptionPane.YES_NO_OPTION);
            if( add == JOptionPane.YES_OPTION){
            limpar();
        }
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            pesquisar();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroContato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tbListaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaPesquisaMouseClicked
       if(evt.getClickCount() == 2){
            setarCampos();
            
           try {
               carregarImagem();
             
           } catch (Exception ex) {
               Logger.getLogger(TelaCadastroContato.class.getName()).log(Level.SEVERE, null, ex);
           }

       }
    }//GEN-LAST:event_tbListaPesquisaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (tbListaPesquisa.getColumnCount() == 0){
            List<Contatos> contatos = new ArrayList<>(); 
            ContatosModel model = new ContatosModel(contatos);
            tbListaPesquisa.setModel(model);
            indiceTabela();
         }
    }//GEN-LAST:event_formWindowActivated

    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
        try {
            pesquisar();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroContato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPesquisarKeyPressed

    private void btnDelatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelatarActionPerformed
        int deletar = JOptionPane.showConfirmDialog(null, "Tem certeza de que deseja excluir o contato?", "Atenção", JOptionPane.YES_NO_OPTION); 
        if (deletar == JOptionPane.YES_OPTION){ 
            deletar();
        }
    }//GEN-LAST:event_btnDelatarActionPerformed

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped
            int n = 2; 
            if(txtEstado.getText().length() >= n){ 
                evt.consume(); 
                JOptionPane.showMessageDialog(rootPane, "Por favor coloque apenas a sigla do estado"); 
            }
            

    }//GEN-LAST:event_txtEstadoKeyTyped

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             txtTelefone.requestFocus();
         }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             txtCelular.requestFocus();
         }
    }//GEN-LAST:event_txtTelefoneKeyPressed

    private void txtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             txtEmail.requestFocus();
         }
    }//GEN-LAST:event_txtCelularKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             txtSkype.requestFocus();
         }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtSkypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkypeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             txtEndereco.requestFocus();
         }
    }//GEN-LAST:event_txtSkypeKeyPressed

    private void txtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             txtBairro.requestFocus();
         }
    }//GEN-LAST:event_txtEnderecoKeyPressed

    private void txtBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             txtCidade.requestFocus();
         }
    }//GEN-LAST:event_txtBairroKeyPressed

    private void txtCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             txtEstado.requestFocus();
         }
    }//GEN-LAST:event_txtCidadeKeyPressed

    private void txtEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             txtCep.requestFocus();
         }
    }//GEN-LAST:event_txtEstadoKeyPressed

    private void txtCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             btnAdicionarFoto.requestFocus();
         }
    }//GEN-LAST:event_txtCepKeyPressed

    private void btnAdicionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
             adicionar();
         }
    }//GEN-LAST:event_btnAdicionarKeyPressed

    private void btnLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
             
           limpar();
         }
    }//GEN-LAST:event_btnLimparKeyPressed

    private void btnAdicionarFotoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarFotoKeyPressed
        adicionarFoto();
    }//GEN-LAST:event_btnAdicionarFotoKeyPressed

    private void btnPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisarKeyPressed
        try {
            pesquisar();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroContato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarKeyPressed

    
    private void adicionarFoto(){
         JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        arquivo =f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(arquivo).getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
        lblFoto.setIcon(imageIcon);
      try {

            File image = new File(arquivo);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
            imagemContato=bos.toByteArray();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }
    
    
    
  private void adicionar(){
        if (txtNome.getText().isEmpty() && txtTelefone.getText().isEmpty() &&  txtCelular.getText().isEmpty() &&  txtEmail.getText().isEmpty() && txtSkype.getText().isEmpty() && txtEndereco.getText().isEmpty() && txtBairro.getText().isEmpty() && txtCidade.getText().isEmpty() && txtEstado.getText().isEmpty() && txtCep.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Impossivel cadastar contato por favor preencha todos os campos"); 
        }else{
            
            Contatos contatos = new Contatos();
            contatos.setNome(txtNome.getText());
            contatos.setTelefone(txtTelefone.getText());
            contatos.setCelular( txtCelular.getText());
            contatos.setEmail(txtEmail.getText());
            contatos.setSkype(txtSkype.getText());
            contatos.setEndereco(txtEndereco.getText());
            contatos.setBairro(txtBairro.getText());
            contatos.setCidade(txtCidade.getText());
            contatos.setEstado(txtEstado.getText());
            contatos.setCep(txtCep.getText());
            contatos.setFoto(imagemContato);
            ContatosDAO conDao = new ContatosDAO();
            conDao.adicionar(contatos);
         
        }
    
    }  
    
    private void editar(){
         int usuId = Integer.parseInt(txtId.getText());
        
        Contatos contato = new Contatos();
        
        contato.setId(usuId);
        contato.setNome(txtNome.getText());
        contato.setTelefone(txtTelefone.getText());
        contato.setCelular( txtCelular.getText());
        contato.setEmail(txtEmail.getText());
        contato.setSkype(txtSkype.getText());
        contato.setEndereco(txtEndereco.getText());
        contato.setBairro(txtBairro.getText());
        contato.setCidade(txtCidade.getText());
        contato.setEstado(txtEstado.getText());
        contato.setCep(txtCep.getText());
        contato.setFoto(imagemContato);
        ContatosDAO conDao = new ContatosDAO();
        conDao.atualizar(contato);
        
        
    }
    
    private void deletar(){
        
        int usuId = Integer.parseInt(txtId.getText());
        
        Contatos contato = new Contatos();
        
        contato.setId(usuId);
        ContatosDAO conDao = new ContatosDAO();
        conDao.deletar(contato);
        limpar();
       
    }
  
  
  
    private void limpar(){
       txtId.setText("");
       txtNome.setText("");
       txtTelefone.setText("");
       txtCelular.setText("");
       txtEmail.setText("");
       txtSkype.setText("");
       txtEndereco.setText("");
       txtBairro.setText("");
       txtCidade.setText("");
       txtEstado.setText("");
       txtCep.setText("");
       lblFoto.setIcon(null);
       
       txtNome.requestFocus();
       btnAdicionar.setEnabled(true);
       btnDelatar.setEnabled(false);
       btnEditar.setEnabled(false);
    }
    
     private void indiceTabela(){
        tbListaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(40); 
         tbListaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(250); 
         tbListaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(100); 
         tbListaPesquisa.getColumnModel().getColumn(3).setPreferredWidth(100); 
         tbListaPesquisa.getColumnModel().getColumn(4).setPreferredWidth(200); 
         tbListaPesquisa.getColumnModel().getColumn(5).setPreferredWidth(100);
         tbListaPesquisa.getColumnModel().getColumn(6).setPreferredWidth(200);
         tbListaPesquisa.getColumnModel().getColumn(7).setPreferredWidth(150);
         tbListaPesquisa.getColumnModel().getColumn(8).setPreferredWidth(250);
         tbListaPesquisa.getColumnModel().getColumn(9).setPreferredWidth(50);
         tbListaPesquisa.getColumnModel().getColumn(10).setPreferredWidth(80);
         //tbListaPesquisa.getColumnModel().getColumn(11).setPreferredWidth(50);
        
         tbListaPesquisa.getTableHeader().setReorderingAllowed(false); 
         tbListaPesquisa.setAutoResizeMode(tbListaPesquisa.AUTO_RESIZE_OFF);
    }
    
    private void pesquisar() throws Exception{
         List<Contatos> contatos = new ContatosDAO().pesquisar(txtPesquisar.getText());
         ContatosModel cmodel = new ContatosModel(contatos);
         tbListaPesquisa.setModel(cmodel);
         indiceTabela();
         
    
    }    
    
    private void setarCampos(){
        int setar = tbListaPesquisa.getSelectedRow();
        txtId.setText(tbListaPesquisa.getModel().getValueAt(setar, 0).toString());
        txtNome.setText(tbListaPesquisa.getModel().getValueAt(setar, 1).toString());
        txtTelefone.setText(tbListaPesquisa.getModel().getValueAt(setar, 2).toString());
        txtCelular.setText(tbListaPesquisa.getModel().getValueAt(setar, 3).toString());
        txtEmail.setText(tbListaPesquisa.getModel().getValueAt(setar, 4).toString());
        txtSkype.setText(tbListaPesquisa.getModel().getValueAt(setar, 5).toString());
        txtEndereco.setText(tbListaPesquisa.getModel().getValueAt(setar, 6).toString());
        txtBairro.setText(tbListaPesquisa.getModel().getValueAt(setar, 7).toString());
        txtCidade.setText(tbListaPesquisa.getModel().getValueAt(setar, 8).toString());
        txtEstado.setText(tbListaPesquisa.getModel().getValueAt(setar, 9).toString());
        txtCep.setText(tbListaPesquisa.getModel().getValueAt(setar, 10).toString());
        
        
        btnAdicionar.setEnabled(false);
        btnDelatar.setEnabled(true);
        btnEditar.setEnabled(true);
    } 
    
    private void carregarImagem() throws Exception{
               
        byte [] contatos = new ContatosDAO().carregarImagem(txtId.getText());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(contatos).getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH));
        lblFoto.setIcon(imageIcon);
 }   
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroContato dialog = new TelaCadastroContato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAdicionarFoto;
    private javax.swing.JButton btnDelatar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemoverFoto;
    private javax.swing.JDesktopPane deskPaineFoto;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSkype;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tbListaPesquisa;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtSkype;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
    private ImageIcon format = null;
    String arquivo = null;
    byte[] imagemContato = null;
    public static JLabel idusu = new JLabel();


}
