/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fid.Tela;




import com.fid.conexao.Conexao;
import com.fid.conexao.IdUsuDAO;
import java.awt.event.KeyEvent;
import java.sql.*; 
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author JEFFERSON
 */
public class TelaLogin extends javax.swing.JFrame {
    
    Connection conn = null; 
    PreparedStatement ps = null; 
    ResultSet rs = null; 
    
    public void logar(){ 
        String sql = "select * from usuario where usu_login=? and usu_senha=?";
        try{ 
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtUsuario.getText()); 
            ps.setString(2, txtSenha.getText()); 
            rs = ps.executeQuery();
            if (rs.next()){ 
                int id =rs.getInt(1);
                IdUsuDAO.usuId = id;
                String perfil = rs.getString(5);
                TelaPrincipal principal = new TelaPrincipal();
                if (perfil.equals("administrador") | perfil.equals("adm")){ 
                    TelaPrincipal.arMenuCadUsuario.setEnabled(true);
                    TelaPrincipal.feMenuLongs.setEnabled(true);
                    TelaPrincipal.btnCadUsuario.setEnabled(true);
                    
                    principal.setVisible(true);
                    TelaPrincipal.nome.setText(rs.getString(2));
                    
                    
                    this.dispose(); 
                   
                    try {
                        
                                   
                        Locale locale = new Locale("pt","BR"); 
                        GregorianCalendar calendar = new GregorianCalendar(); 
                        SimpleDateFormat dataHora = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss",locale);
                        String sqlg = dataHora.format(calendar.getTime());
                        
                        String sqlLong ="insert into longs(usu_id, lon_data, lon_status) values ('"+id+"','"+sqlg+"','Log-in ')";
                        ps=conn.prepareStatement(sqlLong);
                        ps.execute();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e); 
                    }
                }else{
                    principal.setVisible(true);
                    TelaPrincipal.nome.setText(rs.getString(2));
                    this.dispose();
                    try {
                        Locale locale = new Locale("pt","BR"); 
                        GregorianCalendar calendar = new GregorianCalendar(); 
                        SimpleDateFormat dataHora = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss",locale);
                        String sqlg = dataHora.format(calendar.getTime());
                    
                        String sqlLong ="insert into longs(usu_id, lon_data, lon_status) values ('"+id+"','"+sqlg+"','Logado')";
                        ps=conn.prepareStatement(sqlLong);
                        ps.execute();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e); 
                    }
                }
            }else{ 
                JOptionPane.showMessageDialog(null, "usuário e/ou senha inválido."); 
            } 
            }catch(Exception e){ 
                JOptionPane.showMessageDialog(null, e); 
            
            } finally {
                try{
                    ps.close();
                    rs.close();
                    conn.close();
                }catch(Exception e){
                   JOptionPane.showMessageDialog(null,e);
                
                }
            }
        }
    
    /**
     * Creates new form TelaUsuario
     */
    public TelaLogin() {
        initComponents();
        setIconImage(new ImageIcon("Agenda Contatos.png").getImage());
        conn = Conexao.conector();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnEntra = new javax.swing.JToggleButton();
        btnSair = new javax.swing.JToggleButton();
        lblImagem = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/masculine-user-with-suit-tie-and-locked-padlock_icon-icons.com_68295(2).png"))); // NOI18N

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/padlock_icon-icons.com_70907(1).png"))); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });

        btnEntra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEntra.setText("Logar");
        btnEntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntraActionPerformed(evt);
            }
        });
        btnEntra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEntraKeyPressed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/unnamed.png"))); // NOI18N

        lblBemVindo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(0, 51, 204));
        lblBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/AGENDA CONTATOS2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagem)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnEntra, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSenha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblBemVindo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagem)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        setSize(new java.awt.Dimension(635, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntraActionPerformed
        // TODO add your handling code here:
        logar();
    }//GEN-LAST:event_btnEntraActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          txtSenha.requestFocus();

    }//GEN-LAST:event_txtUsuarioKeyPressed
    }
    
    private void btnEntraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEntraKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          logar();
    }//GEN-LAST:event_btnEntraKeyPressed
    }
    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          btnEntra.requestFocus();
    }//GEN-LAST:event_txtSenhaKeyPressed
    }
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed
       

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEntra;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
