/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fid.Tela;


import com.fid.classes.Logs;
import com.fid.classes.SeparatorPanel;
import com.fid.classes.StatusBar;
import com.fid.classes.DataHora;
import com.fid.conexao.LongsDAO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author JEFFERSON
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setIconImage(new ImageIcon("Agenda Contatos.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadContato = new javax.swing.JLabel();
        lblConsuContato = new javax.swing.JLabel();
        lblCadUsuario = new javax.swing.JLabel();
        btnCadContato = new javax.swing.JButton();
        btnConsaContato = new javax.swing.JButton();
        btnCadUsuario = new javax.swing.JButton();
        lblTrocarUsuario = new javax.swing.JLabel();
        btnTrocarUsuario = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        arMenuTrocaUsuario = new javax.swing.JMenuItem();
        menuSeparador1 = new javax.swing.JPopupMenu.Separator();
        arMenuSair = new javax.swing.JMenuItem();
        menuAgenda = new javax.swing.JMenu();
        agMenuCadContato = new javax.swing.JMenuItem();
        arMenuCadUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        agMenuConsContato = new javax.swing.JMenuItem();
        menuFerramenta = new javax.swing.JMenu();
        feMenuLongs = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Agenda de Contato");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblCadContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/green_14392(3).png"))); // NOI18N

        lblConsuContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/find_locate_search_14389(2).png"))); // NOI18N

        lblCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/type_msg_14379(2).png"))); // NOI18N

        btnCadContato.setBackground(new java.awt.Color(28, 122, 28));
        btnCadContato.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadContato.setForeground(new java.awt.Color(255, 255, 255));
        btnCadContato.setText("Cadastrar Contatos");
        btnCadContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadContatoActionPerformed(evt);
            }
        });

        btnConsaContato.setBackground(new java.awt.Color(228, 91, 0));
        btnConsaContato.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConsaContato.setForeground(new java.awt.Color(255, 255, 255));
        btnConsaContato.setText("Consultar Contatos");
        btnConsaContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsaContatoActionPerformed(evt);
            }
        });

        btnCadUsuario.setBackground(new java.awt.Color(102, 102, 0));
        btnCadUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadUsuario.setText("Cadastrar Usuarios");
        btnCadUsuario.setEnabled(false);
        btnCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioActionPerformed(evt);
            }
        });

        lblTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/trocar usuario.png"))); // NOI18N

        btnTrocarUsuario.setBackground(new java.awt.Color(153, 153, 153));
        btnTrocarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTrocarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnTrocarUsuario.setText("Trocar Usuario");
        btnTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarUsuarioActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fid/imagens/stop_close_off_14465(1).png"))); // NOI18N
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSair.setDefaultCapable(false);
        btnSair.setDisabledIcon(null);
        btnSair.setDisabledSelectedIcon(null);
        btnSair.setRequestFocusEnabled(false);
        btnSair.setRolloverEnabled(false);
        btnSair.setVerifyInputWhenFocusTarget(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        menuArquivo.setText("Arquivo");

        arMenuTrocaUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        arMenuTrocaUsuario.setText("Trocar Usuario");
        arMenuTrocaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arMenuTrocaUsuarioActionPerformed(evt);
            }
        });
        menuArquivo.add(arMenuTrocaUsuario);
        menuArquivo.add(menuSeparador1);

        arMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        arMenuSair.setText("Sair");
        arMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                arMenuSairMousePressed(evt);
            }
        });
        menuArquivo.add(arMenuSair);

        jMenuBar1.add(menuArquivo);

        menuAgenda.setText("Agenda");

        agMenuCadContato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        agMenuCadContato.setText("Cadastrar Contato");
        agMenuCadContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agMenuCadContatoActionPerformed(evt);
            }
        });
        menuAgenda.add(agMenuCadContato);

        arMenuCadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        arMenuCadUsuario.setText("Cadastro Usuario");
        arMenuCadUsuario.setEnabled(false);
        arMenuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arMenuCadUsuarioActionPerformed(evt);
            }
        });
        menuAgenda.add(arMenuCadUsuario);
        menuAgenda.add(jSeparator1);

        agMenuConsContato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        agMenuConsContato.setText("Consultar Contato");
        agMenuConsContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agMenuConsContatoActionPerformed(evt);
            }
        });
        menuAgenda.add(agMenuConsContato);

        jMenuBar1.add(menuAgenda);

        menuFerramenta.setText("Ferramenta");

        feMenuLongs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        feMenuLongs.setText("Longs");
        feMenuLongs.setEnabled(false);
        feMenuLongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feMenuLongsActionPerformed(evt);
            }
        });
        menuFerramenta.add(feMenuLongs);

        jMenuBar1.add(menuFerramenta);

        menuAjuda.setText("Ajuda");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuAjuda.add(jMenuItem3);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(btnCadContato, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(lblCadContato)))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsaContato, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblConsuContato)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(btnCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(lblCadUsuario)))
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTrocarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTrocarUsuario)
                                .addGap(41, 41, 41)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblConsuContato)
                            .addGap(18, 18, 18)
                            .addComponent(btnConsaContato, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCadUsuario)
                            .addGap(18, 18, 18)
                            .addComponent(btnCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTrocarUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCadContato)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrocarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(45, 45, 45))
        );

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agMenuCadContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agMenuCadContatoActionPerformed
       TelaCadastroContato cadContato = new TelaCadastroContato(this, true);
       cadContato.setVisible(true);
    }//GEN-LAST:event_agMenuCadContatoActionPerformed

    private void agMenuConsContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agMenuConsContatoActionPerformed
         TelaConsultarContato conContato = new TelaConsultarContato(this, true);
         conContato.setVisible(true);
    }//GEN-LAST:event_agMenuConsContatoActionPerformed

    private void arMenuSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arMenuSairMousePressed
        sair();
    }//GEN-LAST:event_arMenuSairMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sair();
    }//GEN-LAST:event_formWindowClosing

    private void arMenuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arMenuCadUsuarioActionPerformed
        TelaCadastroUsuario cadUsuario = new TelaCadastroUsuario(this, true);
        cadUsuario.setVisible(true);
        
    }//GEN-LAST:event_arMenuCadUsuarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        Container contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());
        
        StatusBar statusBar = new StatusBar();
        
        
        JLabel bemVindo = new JLabel("Bem Vindo");
        bemVindo.setHorizontalAlignment(JLabel.CENTER);
        statusBar.setLeftComponent(bemVindo);
        
        nome.setHorizontalAlignment(JLabel.CENTER);
        statusBar.setLeftComponent(nome);
        
        SeparatorPanel separacao = new SeparatorPanel(Color.GRAY, Color.WHITE);
        statusBar.setLeftComponent(separacao);        
        
        data.setHorizontalAlignment(JLabel.CENTER);
        statusBar.addRightComponent(data);
 

        hora.setHorizontalAlignment(JLabel.CENTER);
        statusBar.addRightComponent(hora);
        
        
        contentPane.add(statusBar, BorderLayout.SOUTH);
        
        DataHora datahora = new DataHora(data, hora);
        datahora.start();
        

    }//GEN-LAST:event_formWindowActivated

    private void feMenuLongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feMenuLongsActionPerformed
        TelaLongs lon =  new TelaLongs(this, true);
        lon.setVisible(true);
    }//GEN-LAST:event_feMenuLongsActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaSobre son =  new TelaSobre(this, true);
        son.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void arMenuTrocaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arMenuTrocaUsuarioActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza de que deseja trocar de usuario?", "Atenção", JOptionPane.YES_NO_OPTION); 
        if (sair == JOptionPane.YES_OPTION){ 
        
                TelaLogin login = new TelaLogin();
                login.setVisible(true);
                this.dispose(); 
                adicionarLong();
        }
    }//GEN-LAST:event_arMenuTrocaUsuarioActionPerformed

    private void btnCadContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadContatoActionPerformed
        TelaCadastroContato cadContato = new TelaCadastroContato(this, true);
       cadContato.setVisible(true);
    }//GEN-LAST:event_btnCadContatoActionPerformed

    private void btnConsaContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsaContatoActionPerformed
         TelaConsultarContato conContato = new TelaConsultarContato(this, true);
         conContato.setVisible(true);
    }//GEN-LAST:event_btnConsaContatoActionPerformed

    private void btnCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioActionPerformed
        TelaCadastroUsuario cadUsuario = new TelaCadastroUsuario(this, true);
        cadUsuario.setVisible(true);
    }//GEN-LAST:event_btnCadUsuarioActionPerformed

    private void btnTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocarUsuarioActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza de que deseja trocar de usuario?", "Atenção", JOptionPane.YES_NO_OPTION); 
        if (sair == JOptionPane.YES_OPTION){ 
        
                TelaLogin login = new TelaLogin();
                login.setVisible(true);
                this.dispose(); 
                adicionarLong();
        }
    }//GEN-LAST:event_btnTrocarUsuarioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       sair();
    }//GEN-LAST:event_btnSairActionPerformed
    
    private void sair(){
         int sair = JOptionPane.showConfirmDialog(null, "Tem certeza de que deseja sair do sistema?", "Atenção", JOptionPane.YES_NO_OPTION); 
                 if (sair == JOptionPane.YES_OPTION){ 
                    
                    adicionarLong();
                    System.exit(0);
                    
                 }else{if(sair == JOptionPane.NO_OPTION){
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                 }
                 }
    }
    
    private void adicionarLong(){
        Logs logs = new Logs();
        LongsDAO longdao = new LongsDAO();
        logs.setStatus("Log-out");
        longdao.longs(logs);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem agMenuCadContato;
    private javax.swing.JMenuItem agMenuConsContato;
    public static javax.swing.JMenuItem arMenuCadUsuario;
    private javax.swing.JMenuItem arMenuSair;
    public static javax.swing.JMenuItem arMenuTrocaUsuario;
    private javax.swing.JButton btnCadContato;
    public static javax.swing.JButton btnCadUsuario;
    private javax.swing.JButton btnConsaContato;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTrocarUsuario;
    public static javax.swing.JMenuItem feMenuLongs;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblCadContato;
    private javax.swing.JLabel lblCadUsuario;
    private javax.swing.JLabel lblConsuContato;
    private javax.swing.JLabel lblTrocarUsuario;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuFerramenta;
    private javax.swing.JPopupMenu.Separator menuSeparador1;
    // End of variables declaration//GEN-END:variables
    public static JLabel nome = new JLabel();
    final JLabel hora = new JLabel();
    final JLabel data = new JLabel();
}
